In [80]:
import pandas as pd

In [81]:
df = pd.read_excel("US-Data_final.xlsx")

In [82]:
df.describe()

1.1      1.3           1.4      1.5           1.6           2.1  \
count  11607.0  11607.0  11607.000000  11607.0  11607.000000  11607.000000   
mean       0.0      0.0      0.917722      0.0      0.387094      0.031877   
std        0.0      0.0      0.274800      0.0      0.487106      0.175681   
min        0.0      0.0      0.000000      0.0      0.000000      0.000000   
25%        0.0      0.0      1.000000      0.0      0.000000      0.000000   
50%        0.0      0.0      1.000000      0.0      0.000000      0.000000   
75%        0.0      0.0      1.000000      0.0      1.000000      0.000000   
max        0.0      0.0      1.000000      0.0      1.000000      1.000000   

           2.2    3.1.1         3.1.2         3.1.3  ...           8.4  \
count  11607.0  11607.0  11607.000000  11607.000000  ...  11607.000000   
mean       0.0      1.0      0.600844      0.553114  ...      0.628931   
std        0.0      0.0      0.489746      0.497192  ...      0.483112   
min        0.0      1.0      0.000000      0.000000  ...      0.000000   
25%        0.0      1.0      0.000000      0.000000  ...      0.000000   
50%        0.0      1.0      1.000000      1.000000  ...      1.000000   
75%        0.0      1.0      1.000000      1.000000  ...      1.000000   
max        0.0      1.0      1.000000      1.000000  ...      1.000000   

         8.4.1    8.4.2      8.5     totalCases        growth     oldGrowth  \
count  11607.0  11607.0  11607.0   11607.000000  11607.000000  11607.000000   
mean       1.0      1.0      1.0   74190.248557      1.084591      1.100931   
std        0.0      0.0      0.0  129590.147813      0.252800      0.303412   
min        1.0      1.0      1.0      20.000000      0.454545      0.454545   
25%        1.0      1.0      1.0    5154.500000      0.973101      0.973166   
50%        1.0      1.0      1.0   26045.000000      1.038841      1.039380   
75%        1.0      1.0      1.0   88721.500000      1.116069      1.118308   
max        1.0      1.0      1.0  936816.000000      5.431010      5.513889   

         activeCases     essential  nonessential  
count   11607.000000  11607.000000  11607.000000  
mean    10897.476609      0.821498      1.204293  
std     18004.612909      0.135656      0.296495  
min         6.000000      0.400000      0.593333  
25%      1522.000000      0.730000      0.990000  
50%      5527.000000      0.820000      1.150000  
75%     12219.000000      0.913333      1.363333  
max    160000.000000      1.440000      3.246667  

[8 rows x 51 columns]

In [83]:
df.columns

Index([       'state',         'date',            1.1,            1.3,
                  1.4,            1.5,            1.6,            2.1,
                  2.2,        '3.1.1',        '3.1.2',        '3.1.3',
              '3.2.1',        '3.2.2',        '4.1.1',        '4.1.2',
              '4.2.1',        '4.2.2',        '4.3.1',        '4.3.2',
              '4.3.3',        '4.3.4',        '4.4.1',        '4.4.2',
              '4.4.3',        '4.5.1',        '4.5.2',        '4.5.3',
              '4.5.4',            5.1,            5.2,            5.3,
                  5.4,            5.5,            5.6,            5.7,
                  5.8,            5.9,            6.1,            6.2,
                  8.1,            8.2,            8.3,            8.4,
              '8.4.1',        '8.4.2',            8.5,   'totalCases',
             'growth',    'oldGrowth',   'flattening',  'activeCases',
          'essential', 'nonessential'],
      dtype='object')

# Data Preprocessing

We drop a few columns if all the values in the column are same. For Eg:

In [84]:
df[8.5].describe()

count    11607.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: 8.5, dtype: float64

In [85]:
df.drop_duplicates(keep=False,inplace=True) 
df_sub = df[['state',1.4,1.6,2.1,'3.1.2','3.1.3','3.2.2','4.1.1','4.1.2','4.2.1','4.2.2','4.3.1',
             '4.3.2','4.3.3','4.3.4','4.4.1','4.4.2','4.5.1','4.5.2','4.5.3','4.5.4',5.1,
             5.3,5.4,5.8,5.9,8.4,'essential','nonessential','growth', 'flattening']]

df_sub is the postprocessed dataframe after removing redundant columns.

In [86]:
df_sub.describe()

1.4           1.6           2.1         3.1.2         3.1.3  \
count  11607.000000  11607.000000  11607.000000  11607.000000  11607.000000   
mean       0.917722      0.387094      0.031877      0.600844      0.553114   
std        0.274800      0.487106      0.175681      0.489746      0.497192   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      0.000000      0.000000      0.000000      0.000000   
50%        1.000000      0.000000      0.000000      1.000000      1.000000   
75%        1.000000      1.000000      0.000000      1.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

              3.2.2         4.1.1         4.1.2         4.2.1         4.2.2  \
count  11607.000000  11607.000000  11607.000000  11607.000000  11607.000000   
mean       0.023262      0.078401      0.996381      0.996985      0.646334   
std        0.150740      0.268813      0.060048      0.054832      0.478128   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      1.000000      1.000000      0.000000   
50%        0.000000      0.000000      1.000000      1.000000      1.000000   
75%        0.000000      0.000000      1.000000      1.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       ...         4.5.4           5.1           5.3           5.4  \
count  ...  11607.000000  11607.000000  11607.000000  11607.000000   
mean   ...      0.045662      0.628500      0.710692      0.995692   
std    ...      0.208760      0.483227      0.453461      0.065495   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      1.000000   
50%    ...      0.000000      1.000000      1.000000      1.000000   
75%    ...      0.000000      1.000000      1.000000      1.000000   
max    ...      1.000000      1.000000      1.000000      1.000000   

                5.8           5.9           8.4     essential  nonessential  \
count  11607.000000  11607.000000  11607.000000  11607.000000  11607.000000   
mean       0.659516      0.977169      0.628931      0.821498      1.204293   
std        0.473892      0.149371      0.483112      0.135656      0.296495   
min        0.000000      0.000000      0.000000      0.400000      0.593333   
25%        0.000000      1.000000      0.000000      0.730000      0.990000   
50%        1.000000      1.000000      1.000000      0.820000      1.150000   
75%        1.000000      1.000000      1.000000      0.913333      1.363333   
max        1.000000      1.000000      1.000000      1.440000      3.246667   

             growth  
count  11607.000000  
mean       1.084591  
std        0.252800  
min        0.454545  
25%        0.973101  
50%        1.038841  
75%        1.116069  
max        5.431010  

[8 rows x 29 columns]

# Divide data into training and testing sets

Each state have rows between 223 to 245. We take first(head) 200 rows of each state for training data and last(tail) 20 rows of each state for testing.

In [87]:
df_sub_train = df_sub.groupby('state').head(200).reset_index(drop=True)
df_sub_test = df_sub.groupby('state').tail(20).reset_index(drop=True)

df_train = df_sub_train[[1.4,1.6,2.1,'3.1.2','3.1.3','3.2.2','4.1.1','4.1.2','4.2.1','4.2.2','4.3.1',
             '4.3.2','4.3.3','4.3.4','4.4.1','4.4.2','4.5.1','4.5.2','4.5.3','4.5.4',5.1,
             5.3,5.4,5.8,5.9,8.4,'essential','nonessential']]
df_train_label = df_sub_train['flattening']

df_test = df_sub_test[[1.4,1.6,2.1,'3.1.2','3.1.3','3.2.2','4.1.1','4.1.2','4.2.1','4.2.2','4.3.1',
             '4.3.2','4.3.3','4.3.4','4.4.1','4.4.2','4.5.1','4.5.2','4.5.3','4.5.4',5.1,
             5.3,5.4,5.8,5.9,8.4,'essential','nonessential']]
df_test_label = df_sub_test['flattening']


# Random Coinflip

In [88]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import pydotplus
import random
import seaborn as sns; sns.set()
from matplotlib import pyplot as plt
%config InlineBackend.figure_format = 'retina'
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import classification_report, confusion_matrix


In [89]:
n = 10000
accuracies = []
for i in range(n):
    y_pred = [random.random() > 0.5 for x in range(len(df_test))]
    report = classification_report(df_test_label, y_pred, output_dict=True)
    accuracies.append(report['accuracy'])

random_dist_avg_correct = sum(accuracies) / len(accuracies)
random_dist_std_dev = (sum([(x - random_dist_avg_correct)**2 for x in accuracies]) / (len(accuracies) - 1)) ** 0.5
print('{:.4f}'.format(random_dist_avg_correct))
print('{:.4f}'.format(random_dist_std_dev))



0.5000
0.0159


# Decision Trees

In [90]:
clf_tree = DecisionTreeClassifier(random_state=100, criterion='gini', max_depth=5)
clf_tree.fit(df_train, df_train_label)

DecisionTreeClassifier(max_depth=5, random_state=100)

In [91]:
y_pred = clf_tree.predict(df_test)

In [92]:
def tree_graph_to_svg(tree, feature_names, svg_file_to_save):
    tree_str = export_graphviz(tree, feature_names=feature_names, 
                                     filled=True, out_file=None, label='root')
    graph = pydotplus.graph_from_dot_data(tree_str)  
    graph.write_svg(svg_file_to_save)

tree_graph_to_svg(clf_tree, [1.4,1.6,2.1,'3.1.2','3.1.3','3.2.2','4.1.1','4.1.2','4.2.1','4.2.2','4.3.1',
             '4.3.2','4.3.3','4.3.4','4.4.1','4.4.2','4.5.1','4.5.2','4.5.3','4.5.4',5.1,
             5.3,5.4,5.8,5.9,8.4,'essential','nonessential'], './covid_decisiontree.svg')

In [93]:

print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[526  13]
 [450  11]]
              precision    recall  f1-score   support

       False       0.54      0.98      0.69       539
        True       0.46      0.02      0.05       461

    accuracy                           0.54      1000
   macro avg       0.50      0.50      0.37      1000
weighted avg       0.50      0.54      0.40      1000



In [94]:
tree_graph_to_svg(tree=clf_tree, feature_names=[1.4,1.6,2.1,'3.1.2','3.1.3','3.2.2','4.1.1','4.1.2','4.2.1','4.2.2','4.3.1',
             '4.3.2','4.3.3','4.3.4','4.4.1','4.4.2','4.5.1','4.5.2','4.5.3','4.5.4',5.1,
             5.3,5.4,5.8,5.9,8.4,'essential','nonessential'], svg_file_to_save='untuned_decisiontree.svg')

## Decision Tree Parameter Optimization

In [95]:
tree_params = [{'criterion': ['gini', 'entropy'], 'max_depth': list(range(1, 24)) + [None]}]

best_search = model_selection.GridSearchCV(estimator = clf_tree, param_grid = tree_params, cv = cv_split, scoring = 'roc_auc')
best_search.fit(df_train, df_train_label)

best_param = best_search.best_params_
print('The best parameter for {} is {}'.format(clf_tree.__class__.__name__, best_param))

The best parameter for DecisionTreeClassifier is {'criterion': 'entropy', 'max_depth': 5}


# Random Forest

In [96]:
from sklearn.ensemble import RandomForestClassifier
rfm = RandomForestClassifier(n_estimators=300, criterion='gini', max_depth=9, oob_score=True)
rfm.fit(df_train, df_train_label)

RandomForestClassifier(max_depth=9, n_estimators=300, oob_score=True)

In [97]:
y_pred = rfm.predict(df_test)

In [98]:
#from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[509  30]
 [429  32]]
              precision    recall  f1-score   support

       False       0.54      0.94      0.69       539
        True       0.52      0.07      0.12       461

    accuracy                           0.54      1000
   macro avg       0.53      0.51      0.41      1000
weighted avg       0.53      0.54      0.43      1000



# Linear SVM

In [99]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', gamma=0.1, decision_function_shape='ovo', probability=True)
svm.fit(df_train, df_train_label)

SVC(decision_function_shape='ovo', gamma=0.1, kernel='linear', probability=True)

In [100]:
y_pred = svm.predict(df_test)

In [101]:
#from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[529  10]
 [451  10]]
              precision    recall  f1-score   support

       False       0.54      0.98      0.70       539
        True       0.50      0.02      0.04       461

    accuracy                           0.54      1000
   macro avg       0.52      0.50      0.37      1000
weighted avg       0.52      0.54      0.39      1000



In [103]:
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process, model_selection

In [104]:
vote_est = vote_est = [
    #Ensemble Methods: http://scikit-learn.org/stable/modules/ensemble.html
    ('rfc', ensemble.RandomForestClassifier()),
    
    #GLM: http://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
    ('lr', linear_model.LogisticRegressionCV()),
    
    #Navies Bayes: http://scikit-learn.org/stable/modules/naive_bayes.html
    ('bnb', naive_bayes.BernoulliNB()),
    ('gnb', naive_bayes.GaussianNB()),
    
    #Nearest Neighbor: http://scikit-learn.org/stable/modules/neighbors.html
    ('knn', neighbors.KNeighborsClassifier()),
    
    #SVM: http://scikit-learn.org/stable/modules/svm.html
    ('svc', svm.SVC(probability=True))

]

In [105]:
cv_split = model_selection.ShuffleSplit(n_splits = 10, test_size = .3, train_size = .7, random_state = 0 )

vote_hard = ensemble.VotingClassifier(estimators = vote_est , voting = 'hard')
vote_hard_cv = model_selection.cross_validate(vote_hard, df_train, df_train_label, return_train_score=True, cv=cv_split)
vote_hard.fit(df_train, df_train_label)

VotingClassifier(estimators=[('rfc', RandomForestClassifier()),
                             ('lr', LogisticRegressionCV()),
                             ('bnb', BernoulliNB()), ('gnb', GaussianNB()),
                             ('knn', KNeighborsClassifier()),
                             ('svc', SVC(probability=True))])

In [106]:
print("Unoptimized")
print('-'*10)
print("Hard Voting Training w/bin score mean: {:.2f}". format(vote_hard_cv['train_score'].mean()*100)) 
print("Hard Voting Test w/bin score mean: {:.2f}". format(vote_hard_cv['test_score'].mean()*100))
print("Hard Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_hard_cv['test_score'].std()*100*3))
print('-'*10)

Unoptimized
----------
Hard Voting Training w/bin score mean: 65.59
Hard Voting Test w/bin score mean: 56.56
Hard Voting Test w/bin score 3*std: +/- 2.52
----------


In [107]:
y_pred = vote_hard.predict(df_test)
print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[535   4]
 [458   3]]
              precision    recall  f1-score   support

       False       0.54      0.99      0.70       539
        True       0.43      0.01      0.01       461

    accuracy                           0.54      1000
   macro avg       0.48      0.50      0.36      1000
weighted avg       0.49      0.54      0.38      1000



In [62]:
import time

The best parameter for DecisionTreeClassifier is {'criterion': 'entropy', 'max_depth': 5}


In [74]:
#Hyperparameter Tune with GridSearchCV: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
grid_n_estimator = [10, 50, 100, 300]
grid_ratio = [.1, .25, .5, .75, 1.0]
grid_max_depth = list(range(1, 24)) + [None]
grid_criterion = ['gini', 'entropy']
grid_bool = [True, False]
grid_seed = [0]

grid_param = [    
            [{
            #RandomForestClassifier - http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier
            'n_estimators': grid_n_estimator, #default=10
            'criterion': grid_criterion, #default=”gini”
            'max_depth': grid_max_depth, #default=None
            'oob_score': [True],
            'random_state': grid_seed
             }],       
    
            [{
            #LogisticRegressionCV - http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html#sklearn.linear_model.LogisticRegressionCV
            'fit_intercept': grid_bool, #default: True
            'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'], #default: lbfgs
            'random_state': grid_seed
             }],
            
    
            [{
            #BernoulliNB - http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB
            'alpha': grid_ratio, #default: 1.0
             }],
    
    
            #GaussianNB - 
            [{}],
    
            [{
            #KNeighborsClassifier - http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier
            'n_neighbors': [1,2,3,4,5,6,7], #default: 5
            'weights': ['uniform', 'distance'], #default = ‘uniform’
            'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
            }],
            
    
            [{
            #SVC - http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC
            #http://blog.hackerearth.com/simple-tutorial-svm-parameter-tuning-python-r
            'C': [1,2,3,4,5], #default=1.0
            'gamma': grid_ratio, #edfault: auto
            'decision_function_shape': ['ovo', 'ovr'], #default:ovr
            'probability': [True],
            'random_state': grid_seed
             }]
        ]

# below commented-out code contains optimimum values determined by gridsearch
# grid_param = [    
#             [{
#             #RandomForestClassifier - http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier
#             'n_estimators': [300], #default=10
#             'criterion': ['entropy'], #default=”gini”
#             'max_depth': [9], #default=None
#             'oob_score': [True], #default=False
#             'random_state': grid_seed
#              }],       
    
#             [{
#             #LogisticRegressionCV - http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html#sklearn.linear_model.LogisticRegressionCV
#             'fit_intercept': [True], #default: True
#             'solver': ['lbfgs'], #default: lbfgs
#             'random_state': grid_seed
#              }],
            
    
#             [{
#             #BernoulliNB - http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB
#             'alpha': [0.1], #default: 1.0
#              }],
    
    
#             #GaussianNB - 
#             [{}],
    
#             [{
#             #KNeighborsClassifier - http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier
#             'n_neighbors': [7], #default: 5
#             'weights': ['distance'], #default = ‘uniform’
#             'algorithm': ['ball_tree']
#             }],
            
    
#             [{
#             #SVC - http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC
#             'C': [1], #default=1.0
#             'gamma': [0.1], #edfault: auto
#             'decision_function_shape': ['ovo'], #default:ovr
#             'probability': [True],
#             'random_state': grid_seed
#              }]
#         ]



start_total = time.perf_counter()
for clf, param in zip (vote_est, grid_param):
    start = time.perf_counter()        
    best_search = model_selection.GridSearchCV(estimator = clf[1], param_grid = param, cv = cv_split, scoring = 'roc_auc')
    best_search.fit(df_train, df_train_label)
    run = time.perf_counter() - start

    best_param = best_search.best_params_
    print('The best parameter for {} is {} with a runtime of {:.2f} seconds.'.format(clf[1].__class__.__name__, best_param, run))
    clf[1].set_params(**best_param) 


run_total = time.perf_counter() - start_total
print('Total optimization time was {:.2f} minutes.'.format(run_total/60))

print('-'*10)

The best parameter for RandomForestClassifier is {'criterion': 'entropy', 'max_depth': 9, 'n_estimators': 300, 'oob_score': True, 'random_state': 0} with a runtime of 804.28 seconds.
The best parameter for LogisticRegressionCV is {'fit_intercept': True, 'random_state': 0, 'solver': 'lbfgs'} with a runtime of 136.77 seconds.
The best parameter for BernoulliNB is {'alpha': 0.1} with a runtime of 0.35 seconds.
The best parameter for GaussianNB is {} with a runtime of 0.07 seconds.
The best parameter for KNeighborsClassifier is {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'distance'} with a runtime of 125.53 seconds.
The best parameter for SVC is {'C': 1, 'decision_function_shape': 'ovo', 'gamma': 0.1, 'probability': True, 'random_state': 0} with a runtime of 3836.49 seconds.
Total optimization time was 81.72 minutes.
----------


In [75]:

vote_hard = ensemble.VotingClassifier(estimators = vote_est , voting = 'hard')
vote_hard_cv = model_selection.cross_validate(vote_hard, df_train, df_train_label, return_train_score=True, cv=cv_split)
vote_hard.fit(df_train, df_train_label)
print("Hard Voting Training w/bin score mean: {:.2f}". format(vote_hard_cv['train_score'].mean()*100)) 
print("Hard Voting Test w/bin score mean: {:.2f}". format(vote_hard_cv['test_score'].mean()*100))
print("Hard Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_hard_cv['test_score'].std()*100*3))
print('-'*10)

Hard Voting Training w/bin score mean: 64.72
Hard Voting Test w/bin score mean: 56.82
Hard Voting Test w/bin score 3*std: +/- 2.20
----------


In [76]:
y_pred = vote_hard.predict(df_test)
print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[534   5]
 [456   5]]
              precision    recall  f1-score   support

       False       0.54      0.99      0.70       539
        True       0.50      0.01      0.02       461

    accuracy                           0.54      1000
   macro avg       0.52      0.50      0.36      1000
weighted avg       0.52      0.54      0.39      1000



In [77]:
vote_soft = ensemble.VotingClassifier(estimators = vote_est , voting = 'soft')
vote_soft_cv = model_selection.cross_validate(vote_soft, df_train, df_train_label, return_train_score=True, cv=cv_split)
vote_soft.fit(df_train, df_train_label)
print("Soft Voting Training w/bin score mean: {:.2f}". format(vote_soft_cv['train_score'].mean()*100)) 
print("Soft Voting Test w/bin score mean: {:.2f}". format(vote_soft_cv['test_score'].mean()*100))
print("Soft Voting Test w/bin score 3*std: +/- {:.2f}". format(vote_soft_cv['test_score'].std()*100*3))
print('-'*10)

Soft Voting Training w/bin score mean: 76.75
Soft Voting Test w/bin score mean: 56.88
Soft Voting Test w/bin score 3*std: +/- 2.95
----------


In [78]:
y_pred = vote_soft.predict(df_test)
print(confusion_matrix(df_test_label, y_pred))
print(classification_report(df_test_label, y_pred))

[[539   0]
 [461   0]]
              precision    recall  f1-score   support

       False       0.54      1.00      0.70       539
        True       0.00      0.00      0.00       461

    accuracy                           0.54      1000
   macro avg       0.27      0.50      0.35      1000
weighted avg       0.29      0.54      0.38      1000

